# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/main.xdc

# Block Designs: bd/TestBlockDesign/TestBlockDesign.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TestBlockDesign || ORIG_REF_NAME==TestBlockDesign} -quiet] -quiet

# IP: bd/TestBlockDesign/ip/TestBlockDesign_VGA_Controller_0_0/TestBlockDesign_VGA_Controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TestBlockDesign_VGA_Controller_0_0 || ORIG_REF_NAME==TestBlockDesign_VGA_Controller_0_0} -quiet] -quiet

# IP: bd/TestBlockDesign/ip/TestBlockDesign_blk_mem_gen_0_0/TestBlockDesign_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TestBlockDesign_blk_mem_gen_0_0 || ORIG_REF_NAME==TestBlockDesign_blk_mem_gen_0_0} -quiet] -quiet

# XDC: d:/FPGA_CPU/vivado/VGA_Controller/VGA_Controller.gen/sources_1/bd/TestBlockDesign/TestBlockDesign_ooc.xdc
