@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Dec 04 23:11:36 +0100 2024
REM SW Build 5076996 on Wed May 22 18:37:14 MDT 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim PipeliningSimulation_behav -key {Behavioral:sim_1:Functional:PipeliningSimulation} -tclbatch PipeliningSimulation.tcl -view D:/Programmieren/Projekte/FPGA_CPU/SixteenShadesOfCpu/vivado/Pipelining/Pipelining_Controller_SIM_behav.wcfg -view D:/Programmieren/Projekte/FPGA_CPU/SixteenShadesOfCpu/vivado/Pipelining/Pipelining_Forwarder_SIM_behav.wcfg -view D:/Programmieren/Projekte/FPGA_CPU/SixteenShadesOfCpu/vivado/Pipelining/Pipelining_ExecutionStage_SIM_behav.wcfg -view D:/Programmieren/Projekte/FPGA_CPU/SixteenShadesOfCpu/vivado/Pipelining/Pipelining_WriteBackStage_SIM_behav.wcfg -log simulate.log"
call xsim  PipeliningSimulation_behav -key {Behavioral:sim_1:Functional:PipeliningSimulation} -tclbatch PipeliningSimulation.tcl -view D:/Programmieren/Projekte/FPGA_CPU/SixteenShadesOfCpu/vivado/Pipelining/Pipelining_Controller_SIM_behav.wcfg -view D:/Programmieren/Projekte/FPGA_CPU/SixteenShadesOfCpu/vivado/Pipelining/Pipelining_Forwarder_SIM_behav.wcfg -view D:/Programmieren/Projekte/FPGA_CPU/SixteenShadesOfCpu/vivado/Pipelining/Pipelining_ExecutionStage_SIM_behav.wcfg -view D:/Programmieren/Projekte/FPGA_CPU/SixteenShadesOfCpu/vivado/Pipelining/Pipelining_WriteBackStage_SIM_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
