# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Entwicklung/SixteenShadesOfCpu/vivado/memory_tryout/memory_tryout.srcs/sources_1/bd/main_block/ip/main_block_blk_mem_gen_0_0/main_block_blk_mem_gen_0_0.xci
# IP: The module: 'main_block_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Entwicklung/SixteenShadesOfCpu/vivado/memory_tryout/memory_tryout.gen/sources_1/bd/main_block/ip/main_block_blk_mem_gen_0_0/main_block_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_block_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Entwicklung/SixteenShadesOfCpu/vivado/memory_tryout/memory_tryout.srcs/sources_1/bd/main_block/ip/main_block_blk_mem_gen_0_0/main_block_blk_mem_gen_0_0.xci
# IP: The module: 'main_block_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Entwicklung/SixteenShadesOfCpu/vivado/memory_tryout/memory_tryout.gen/sources_1/bd/main_block/ip/main_block_blk_mem_gen_0_0/main_block_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_block_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
