# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/main.xdc

# Block Designs: bd/main/main.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main || ORIG_REF_NAME==main} -quiet] -quiet

# IP: bd/main/ip/main_Pipelining_Controller_0_0/main_Pipelining_Controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_Pipelining_Controller_0_0 || ORIG_REF_NAME==main_Pipelining_Controller_0_0} -quiet] -quiet

# IP: bd/main/ip/main_CU_Decoder_0_0/main_CU_Decoder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_CU_Decoder_0_0 || ORIG_REF_NAME==main_CU_Decoder_0_0} -quiet] -quiet

# IP: bd/main/ip/main_Decoder_0_0/main_Decoder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_Decoder_0_0 || ORIG_REF_NAME==main_Decoder_0_0} -quiet] -quiet

# IP: bd/main/ip/main_RegFile_0_0/main_RegFile_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_RegFile_0_0 || ORIG_REF_NAME==main_RegFile_0_0} -quiet] -quiet

# IP: bd/main/ip/main_Pipelining_Forwarder_0_0/main_Pipelining_Forwarder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_Pipelining_Forwarder_0_0 || ORIG_REF_NAME==main_Pipelining_Forwarder_0_0} -quiet] -quiet

# IP: bd/main/ip/main_Pipelining_Execution_0_0/main_Pipelining_Execution_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_Pipelining_Execution_0_0 || ORIG_REF_NAME==main_Pipelining_Execution_0_0} -quiet] -quiet

# IP: bd/main/ip/main_CU_RAMAddressControl_0_0/main_CU_RAMAddressControl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_CU_RAMAddressControl_0_0 || ORIG_REF_NAME==main_CU_RAMAddressControl_0_0} -quiet] -quiet

# IP: bd/main/ip/main_ALU_0_0/main_ALU_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_ALU_0_0 || ORIG_REF_NAME==main_ALU_0_0} -quiet] -quiet

# IP: bd/main/ip/main_CU_ImmediateManipula_0_0/main_CU_ImmediateManipula_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_CU_ImmediateManipula_0_0 || ORIG_REF_NAME==main_CU_ImmediateManipula_0_0} -quiet] -quiet

# IP: bd/main/ip/main_CU_JumpDestinationSe_0_0/main_CU_JumpDestinationSe_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_CU_JumpDestinationSe_0_0 || ORIG_REF_NAME==main_CU_JumpDestinationSe_0_0} -quiet] -quiet

# IP: bd/main/ip/main_CU_JumpController_0_0/main_CU_JumpController_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_CU_JumpController_0_0 || ORIG_REF_NAME==main_CU_JumpController_0_0} -quiet] -quiet

# IP: bd/main/ip/main_CU_WriteSelector_0_0/main_CU_WriteSelector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_CU_WriteSelector_0_0 || ORIG_REF_NAME==main_CU_WriteSelector_0_0} -quiet] -quiet

# IP: bd/main/ip/main_Pipelining_WriteBack_0_0/main_Pipelining_WriteBack_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_Pipelining_WriteBack_0_0 || ORIG_REF_NAME==main_Pipelining_WriteBack_0_0} -quiet] -quiet

# IP: bd/main/ip/main_IROM_0_1/main_IROM_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_IROM_0_1 || ORIG_REF_NAME==main_IROM_0_1} -quiet] -quiet

# IP: bd/main/ip/main_RAM_Placeholder_0_0/main_RAM_Placeholder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_RAM_Placeholder_0_0 || ORIG_REF_NAME==main_RAM_Placeholder_0_0} -quiet] -quiet

# IP: bd/main/ip/main_ALU_FLAG_PACKER_0_1/main_ALU_FLAG_PACKER_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_ALU_FLAG_PACKER_0_1 || ORIG_REF_NAME==main_ALU_FLAG_PACKER_0_1} -quiet] -quiet

# IP: bd/main/ip/main_ProgramCounter_0_1/main_ProgramCounter_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_ProgramCounter_0_1 || ORIG_REF_NAME==main_ProgramCounter_0_1} -quiet] -quiet

# XDC: d:/FPGA_CPU/vivado/Integration/Integration.gen/sources_1/bd/main/main_ooc.xdc
