# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/main.xdc

# Block Designs: bd/main/main.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main || ORIG_REF_NAME==main} -quiet] -quiet

# IP: bd/main/ip/main_Pipelining_Controller_0_0/main_Pipelining_Controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_Pipelining_Controller_0_0 || ORIG_REF_NAME==main_Pipelining_Controller_0_0} -quiet] -quiet

# IP: bd/main/ip/main_ProgramCounter_0_0/main_ProgramCounter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_ProgramCounter_0_0 || ORIG_REF_NAME==main_ProgramCounter_0_0} -quiet] -quiet

# IP: bd/main/ip/main_CU_Decoder_0_0/main_CU_Decoder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_CU_Decoder_0_0 || ORIG_REF_NAME==main_CU_Decoder_0_0} -quiet] -quiet

# IP: bd/main/ip/main_Decoder_0_0/main_Decoder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_Decoder_0_0 || ORIG_REF_NAME==main_Decoder_0_0} -quiet] -quiet

# IP: bd/main/ip/main_RegFile_0_0/main_RegFile_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_RegFile_0_0 || ORIG_REF_NAME==main_RegFile_0_0} -quiet] -quiet

# IP: bd/main/ip/main_Pipelining_Forwarder_0_0/main_Pipelining_Forwarder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_Pipelining_Forwarder_0_0 || ORIG_REF_NAME==main_Pipelining_Forwarder_0_0} -quiet] -quiet

# IP: bd/main/ip/main_Pipelining_Execution_0_0/main_Pipelining_Execution_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_Pipelining_Execution_0_0 || ORIG_REF_NAME==main_Pipelining_Execution_0_0} -quiet] -quiet

# IP: bd/main/ip/main_CU_RAMAddressControl_0_0/main_CU_RAMAddressControl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_CU_RAMAddressControl_0_0 || ORIG_REF_NAME==main_CU_RAMAddressControl_0_0} -quiet] -quiet

# IP: bd/main/ip/main_ALU_0_0/main_ALU_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_ALU_0_0 || ORIG_REF_NAME==main_ALU_0_0} -quiet] -quiet

# IP: bd/main/ip/main_CU_ImmediateManipula_0_0/main_CU_ImmediateManipula_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_CU_ImmediateManipula_0_0 || ORIG_REF_NAME==main_CU_ImmediateManipula_0_0} -quiet] -quiet

# IP: bd/main/ip/main_CU_JumpDestinationSe_0_0/main_CU_JumpDestinationSe_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_CU_JumpDestinationSe_0_0 || ORIG_REF_NAME==main_CU_JumpDestinationSe_0_0} -quiet] -quiet

# IP: bd/main/ip/main_CU_JumpController_0_0/main_CU_JumpController_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_CU_JumpController_0_0 || ORIG_REF_NAME==main_CU_JumpController_0_0} -quiet] -quiet

# IP: bd/main/ip/main_CU_WriteSelector_0_0/main_CU_WriteSelector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_CU_WriteSelector_0_0 || ORIG_REF_NAME==main_CU_WriteSelector_0_0} -quiet] -quiet

# IP: bd/main/ip/main_Pipelining_WriteBack_0_0/main_Pipelining_WriteBack_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_Pipelining_WriteBack_0_0 || ORIG_REF_NAME==main_Pipelining_WriteBack_0_0} -quiet] -quiet

# IP: bd/main/ip/main_ALU_FLAG_PACKER_0_1/main_ALU_FLAG_PACKER_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_ALU_FLAG_PACKER_0_1 || ORIG_REF_NAME==main_ALU_FLAG_PACKER_0_1} -quiet] -quiet

# IP: bd/main/ip/main_clockcontroller_0_0/main_clockcontroller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_clockcontroller_0_0 || ORIG_REF_NAME==main_clockcontroller_0_0} -quiet] -quiet

# IP: bd/main/ip/main_mmu_0_0/main_mmu_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_mmu_0_0 || ORIG_REF_NAME==main_mmu_0_0} -quiet] -quiet

# IP: bd/main/ip/main_mmio_0_0/main_mmio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_mmio_0_0 || ORIG_REF_NAME==main_mmio_0_0} -quiet] -quiet

# IP: bd/main/ip/main_blk_mem_gen_0_0/main_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_blk_mem_gen_0_0 || ORIG_REF_NAME==main_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/main/ip/main_clk_wiz_0_0/main_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_clk_wiz_0_0 || ORIG_REF_NAME==main_clk_wiz_0_0} -quiet] -quiet

# IP: bd/main/ip/main_Debugger_0_0/main_Debugger_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_Debugger_0_0 || ORIG_REF_NAME==main_Debugger_0_0} -quiet] -quiet

# IP: bd/main/ip/main_RX_UART_0_0/main_RX_UART_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_RX_UART_0_0 || ORIG_REF_NAME==main_RX_UART_0_0} -quiet] -quiet

# IP: bd/main/ip/main_TX_UART_0_0/main_TX_UART_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_TX_UART_0_0 || ORIG_REF_NAME==main_TX_UART_0_0} -quiet] -quiet

# IP: bd/main/ip/main_VGA_CPU_Bridge_0_0/main_VGA_CPU_Bridge_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_VGA_CPU_Bridge_0_0 || ORIG_REF_NAME==main_VGA_CPU_Bridge_0_0} -quiet] -quiet

# IP: bd/main/ip/main_GPU_0_0/main_GPU_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_GPU_0_0 || ORIG_REF_NAME==main_GPU_0_0} -quiet] -quiet

# IP: bd/main/ip/main_VGA_Controller_0_0/main_VGA_Controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_VGA_Controller_0_0 || ORIG_REF_NAME==main_VGA_Controller_0_0} -quiet] -quiet

# XDC: c:/Development/SixteenShadesOfCpu/vivado/Integration/Integration.gen/sources_1/bd/main/ip/main_blk_mem_gen_0_0/main_blk_mem_gen_0_0_ooc.xdc

# XDC: c:/Development/SixteenShadesOfCpu/vivado/Integration/Integration.gen/sources_1/bd/main/ip/main_clk_wiz_0_0/main_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==main_clk_wiz_0_0 || ORIG_REF_NAME==main_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Development/SixteenShadesOfCpu/vivado/Integration/Integration.gen/sources_1/bd/main/ip/main_clk_wiz_0_0/main_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==main_clk_wiz_0_0 || ORIG_REF_NAME==main_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Development/SixteenShadesOfCpu/vivado/Integration/Integration.gen/sources_1/bd/main/ip/main_clk_wiz_0_0/main_clk_wiz_0_0_ooc.xdc

# XDC: c:/Development/SixteenShadesOfCpu/vivado/Integration/Integration.gen/sources_1/bd/main/main_ooc.xdc
